rule AUTO_loki_a_v1 {
   meta:
      description = "loki: strings selected by yarGen from the family's samples. Generated by AegisLattice yara-forge and promoted only after 0 hits on 44,258 clean files, 0 hits on other families, and hits on held-out samples it was not built from; monitored in production and retired if precision drops."
      author = "Tao Goldi (AegisLattice yara-forge, generated and validated automatically)"
      reference = "https://taogoldi.github.io/reverse-engineer/"
      license = "MIT"
      family = "loki"
      date = "2026-09-23"
      version = 1
      generator = "yara-forge/yargen-go"
      label_basis = "oracle-labelled samples (decoded config, MOTIF, MCRIT, VirusTotal, abuse.ch)"
      training_samples = 40
      validation_goodware_files = 44258
      validation_goodware_hits = 0
      validation_other_families = 258
      validation_other_family_hits = 0
      validation_heldout_hits = "3 of 60"
      live_precision = "1.00 over 4 matches"
      live_measured = "2026-09-24"
      hash1 = "c6df74426be4447e6956ec541c65e8a3dbd7136fb86c1a173ef336110d985c22"
      hash2 = "dadf297d60f465883336bd72b69fafbaba821fa0cc580d802b7f50e94c08793e"
      hash3 = "652a323b76a64c51111ed62e9a6096e5e925b7ee0b1f2700a38be486c9825550"
   strings:
      $s1 = "SELECT encryptedUsername, encryptedPassword, formSubmitURL, hostname FROM moz_logins" fullword ascii
      $s2 = "vaultcli.dll" fullword wide /* goodware: 10, reversed encoded */
      $s3 = "sCrypt32.dll" fullword wide
      $s4 = "nss3.dll" fullword wide /* goodware: 5 */
      $s5 = "%s\\%s\\%s.exe" fullword wide
      $s6 = "mozsqlite3.dll" fullword wide /* goodware: 8 */
      $s7 = "%s\\nss3.dll" fullword wide
      $s8 = "%s\\%s\\User Data\\Default\\Login Data" fullword wide
      $s9 = "%s\\32BitFtp.TMP" fullword wide
      $s10 = "%s\\GoFTP\\settings\\Connections.txt" fullword wide
      $s11 = "Software\\Microsoft\\Windows NT\\CurrentVersion\\Windows Messaging Subsystem\\Profiles\\Outlook" fullword wide
      $s12 = "%s\\Notepad++\\plugins\\config\\NppFTP\\NppFTP.xml" fullword wide
      $s13 = "%s\\FTPShell\\ftpshell.fsi" fullword wide
      $s14 = "More information: http://www.ibsensoftware.com/" fullword ascii
      $s15 = "signons.txt" fullword wide /* goodware: 2 */
      $s16 = "signons3.txt" fullword wide /* goodware: 2 */
      $s17 = "Software\\Far2\\Plugins\\FTP\\Hosts" fullword wide
      $s18 = "FtpPassword" fullword wide
      $s19 = "Software\\9bis.com\\KiTTY\\Sessions" fullword wide
      $s20 = "wand.dat" fullword wide /* goodware: 2 */
   condition:
      uint16(0) == 0x5a4d and filesize < 2000KB and 8 of ($s*)
}