rule AUTO_guloader_a_v3 {
   meta:
      description = "guloader: strings selected by yarGen from the family's samples. Generated by AegisLattice yara-forge and promoted only after 0 hits on 48,864 clean files, 0 hits on other families, and hits on held-out samples it was not built from; monitored in production and retired if precision drops."
      author = "Tao Goldi (AegisLattice yara-forge, generated and validated automatically)"
      reference = "https://taogoldi.github.io/reverse-engineer/"
      license = "MIT"
      family = "guloader"
      date = "2026-10-07"
      version = 3
      generator = "yara-forge/yargen-go"
      label_basis = "oracle-labelled samples (decoded config, MOTIF, MCRIT, VirusTotal, abuse.ch)"
      training_samples = 40
      validation_goodware_files = 48864
      validation_goodware_hits = 0
      validation_other_families = 429
      validation_other_family_hits = 0
      validation_heldout_hits = "8 of 60"
      hash1 = "14f5baba86e43ea12f13c38bac263bd7a0a58de989378f52033f2fc282b0f64f"
      hash2 = "54a6a8534a00d3b362bab5695a5a08db7785a533e30e23482c737fd029d96da5"
      hash3 = "966a83b93adbebe4af088f1395a3214d22420a2c07e7a4b66576dba3dc4682c8"
   strings:
      $s1 = "Attakeret.exe" fullword wide
      $s2 = "Hello World!" fullword ascii /* goodware: 1 */
      $s3 = "|$$InstuZ" fullword ascii
      $s4 = "|$ softuP" fullword ascii
      $s5 = "D$HtoSIBUR" fullword ascii
      $s6 = "D$H9l$4uyj" fullword ascii
      $s7 = "Zt=f9T$@t6f" fullword ascii
      $s8 = "9l$4t#9l$0t" fullword ascii
      $s9 = "G9l$8u'j" fullword ascii
      $s10 = "L$P9l$8t" fullword ascii
      $s11 = "j\"^j [f;" fullword ascii
      $s12 = "D$ MPUhs" fullword ascii
      $s13 = "j.Xf9D$Hu" fullword ascii
      $s14 = "thf9D$Ju" fullword ascii
      $s15 = "D$H*L$l#" fullword ascii
      $s16 = "Questar Corp" fullword wide
      $s17 = "YYPV9l$<u" fullword ascii
      $s18 = "Conectiv, Inc" fullword wide
   condition:
      uint16(0) == 0x5a4d and filesize < 1000KB and 8 of ($s*)
}