rule AUTO_guloader_b_v4 {
   meta:
      description = "guloader: strings selected by yarGen from the family's samples. Generated by AegisLattice yara-forge and promoted only after 0 hits on 48,864 clean files, 0 hits on other families, and hits on held-out samples it was not built from; monitored in production and retired if precision drops."
      author = "Tao Goldi (AegisLattice yara-forge, generated and validated automatically)"
      reference = "https://taogoldi.github.io/reverse-engineer/"
      license = "MIT"
      family = "guloader"
      date = "2026-10-09"
      version = 4
      generator = "yara-forge/yargen-go"
      label_basis = "oracle-labelled samples (decoded config, MOTIF, MCRIT, VirusTotal, abuse.ch)"
      training_samples = 40
      validation_goodware_files = 48864
      validation_goodware_hits = 0
      validation_other_families = 447
      validation_other_family_hits = 0
      validation_heldout_hits = "8 of 60"
      hash1 = "14f5baba86e43ea12f13c38bac263bd7a0a58de989378f52033f2fc282b0f64f"
      hash2 = "54a6a8534a00d3b362bab5695a5a08db7785a533e30e23482c737fd029d96da5"
      hash3 = "966a83b93adbebe4af088f1395a3214d22420a2c07e7a4b66576dba3dc4682c8"
   strings:
      $s1 = "Hello World!" fullword ascii /* goodware: 1 */
      $s2 = "~nsu%X.tmp" fullword ascii
      $s3 = "attemptable ponchoers" fullword wide
      $s4 = "speedbaad" fullword wide
      $s5 = "enevoldsherredmmet tegneseriers" fullword wide
      $s6 = "workrooms tuffaceous reimposure" fullword wide
      $s7 = "D$0;D$<|" fullword ascii /* goodware: 3 */
      $s8 = "|$ NulluI" fullword ascii
      $s9 = "|$(Instu]" fullword ascii
      $s10 = "|$$softuS" fullword ascii
      $s11 = "9\\$4t#9\\$0t" fullword ascii
      $s12 = "D$ OPWh-" fullword ascii
      $s13 = "t09\\$4uf" fullword ascii
      $s14 = "L$T9\\$8t" fullword ascii
      $s15 = "-fffH~~~" fullword ascii
      $s16 = "\"WUU~oik" fullword ascii
      $s17 = "F9\\$8u'j" fullword ascii
      $s18 = "|$D9\\$8t" fullword ascii
      $s19 = "YYPV9\\$<u" fullword ascii
      $s20 = " s59=l(z" fullword ascii
   condition:
      uint16(0) == 0x5a4d and filesize < 12000KB and 8 of ($s*)
}