rule AUTO_amadey_b_v1 {
   meta:
      description = "amadey: strings selected by yarGen from the family's samples. Generated by AegisLattice yara-forge and promoted only after 0 hits on 41,717 clean files, 0 hits on other families, and hits on held-out samples it was not built from; monitored in production and retired if precision drops."
      author = "Tao Goldi (AegisLattice yara-forge, generated and validated automatically)"
      reference = "https://taogoldi.github.io/reverse-engineer/"
      license = "MIT"
      family = "amadey"
      date = "2026-09-20"
      version = 1
      generator = "yargen-go"
      label_basis = "oracle-labelled samples (decoded config, MOTIF, MCRIT, VirusTotal, abuse.ch)"
      training_samples = 40
      validation_goodware_files = 41717
      validation_goodware_hits = 0
      validation_other_families = 126
      validation_other_family_hits = 0
      validation_heldout_hits = "3 of 60"
      live_precision = "0.90 over 125 matches"
      live_measured = "2026-09-24"
      hash1 = "920039788b3a1620bbafc5b02d10827ce68ec4bb6f9088014f76c8eecb01875d"
      hash2 = "9b85ae26f1588d1238395258076430b282476882128aeec79066bf10af37d8e2"
      hash3 = "817d481b633a5fd64cd7cae774a4fcde3ceba390bd70e8069f1010a17a4f59f9"
   strings:
      $s1 = "CLIPPERDLL.dll" fullword ascii
      $s2 = "9':1:;:R:\\:" fullword ascii
      $s3 = "QGdqPneR9U6dYTHhdaxuO1TlZvzpZ0KhBHSSPYKc" fullword ascii
      $s4 = "QH4h5nyjUEqdYTHhdaxuO1TlZvzpZ0KhBHSSPYKc" fullword ascii
      $s5 = "9 9(90949<9P9p9" fullword ascii /* goodware: 1 */
      $s6 = "7$7,70747<7P7X7`7h7l7p7x7" fullword ascii /* goodware: 1 */
      $s7 = ">$><>@>X>\\>t>" fullword ascii /* goodware: 1 */
      $s8 = "4&5k5p5t5x5|5" fullword ascii /* goodware: 1 */
      $s9 = "4*414R4{4" fullword ascii /* goodware: 1 */
      $s10 = "<2<<<g<q<{<" fullword ascii /* goodware: 1 */
      $s11 = "3'414;4R4\\4" fullword ascii /* goodware: 2 */
      $s12 = ":';1;;;R;\\;" fullword ascii /* goodware: 2 */
      $s13 = "626<6g6q6{6" fullword ascii /* goodware: 2 */
      $s14 = "5G5Q5[5r5|5" fullword ascii /* goodware: 2 */
      $s15 = "5o0S43 890Cieevhfzxl3rSkeyLp0kqhSUGmPXUcKO==" fullword ascii
      $s16 = "=G=Q=[=r=|=" fullword ascii /* goodware: 2 */
      $s17 = "2G2Q2[2r2|2" fullword ascii /* goodware: 2 */
      $s18 = "0'111;1R1\\1" fullword ascii /* goodware: 2 */
      $s19 = "020<0g0q0{0" fullword ascii /* goodware: 2 */
      $s20 = "?G?Q?[?r?|?" fullword ascii /* goodware: 2 */
   condition:
      uint16(0) == 0x5a4d and filesize < 400KB and 8 of ($s*)
}