rule AUTO_adwareneoreklami_a_v1 {
   meta:
      description = "adwareneoreklami: strings selected by yarGen from the family's samples. Generated by AegisLattice yara-forge and promoted only after 0 hits on 48,864 clean files, 0 hits on other families, and hits on held-out samples it was not built from; monitored in production and retired if precision drops."
      author = "Tao Goldi (AegisLattice yara-forge, generated and validated automatically)"
      reference = "https://taogoldi.github.io/reverse-engineer/"
      license = "MIT"
      family = "adwareneoreklami"
      date = "2026-09-27"
      version = 1
      generator = "yara-forge/yargen-go"
      label_basis = "oracle-labelled samples (decoded config, MOTIF, MCRIT, VirusTotal, abuse.ch)"
      training_samples = 40
      validation_goodware_files = 48864
      validation_goodware_hits = 0
      validation_other_families = 265
      validation_other_family_hits = 0
      validation_heldout_hits = "60 of 60"
      live_precision = "1.00 over 179 matches"
      live_measured = "2026-09-28"
      hash1 = "436d6e12fda2a669bf1cb8a46698578f7dbf6d6e9352485b965537a8037c496e"
      hash2 = "72e5766a1923f703b842bd2252aafb6ef0842821862b82ccb9ff288a973a57af"
      hash3 = "9146cee3d387cb3d665885b95d885734541f281cbb2a4726b6a59df922a83ee7"
   strings:
      $s1 = "7zS.sfx.exe" fullword wide
      $s2 = "ExecuteParameters" fullword wide /* goodware: 2 */
      $s3 = "ExecuteFile" fullword wide /* goodware: 2 */
      $s4 = "Can not find setup.exe" fullword wide
      $s5 = "RunProgram=\"Install.exe \"" fullword ascii
      $s6 = "       <requestedExecutionLevel level=\"requireAdministrator\"/>" fullword ascii
      $s7 = "Config failed" fullword wide
      $s8 = "82R.XBF*qo" fullword ascii
      $s9 = "j:\"r9H<%" fullword ascii
      $s10 = "N:\"OQ*p.(" fullword ascii
      $s11 = "RunProgram" fullword wide /* goodware: 2 */
      $s12 = "4[>cMeye" fullword ascii
      $s13 = "6oyc /YB" fullword ascii
      $s14 = "* |v73^\\" fullword ascii
      $s15 = "8/lle.YwA" fullword ascii
      $s16 = "B.Lkk=E5" fullword ascii
      $s17 = "m3#9.JrC" fullword ascii
      $s18 = "Can not create temp folder archive" fullword wide
      $s19 = ".RAU\\wd&" fullword ascii
      $s20 = ",!@Install@!UTF-8!" fullword ascii /* goodware: 2 */
   condition:
      uint16(0) == 0x5a4d and filesize < 21000KB and 8 of ($s*)
}