rule AUTO_asyncrat_a_v7 {
   meta:
      description = "asyncrat: strings selected by yarGen from the family's samples. Generated by AegisLattice yara-forge and promoted only after 0 hits on 48,864 clean files, 0 hits on other families, and hits on held-out samples it was not built from; monitored in production and retired if precision drops."
      author = "Tao Goldi (AegisLattice yara-forge, generated and validated automatically)"
      reference = "https://taogoldi.github.io/reverse-engineer/"
      license = "MIT"
      family = "asyncrat"
      date = "2026-10-07"
      version = 7
      generator = "yara-forge/yargen-go"
      label_basis = "oracle-labelled samples (decoded config, MOTIF, MCRIT, VirusTotal, abuse.ch)"
      training_samples = 40
      validation_goodware_files = 48864
      validation_goodware_hits = 0
      validation_other_families = 429
      validation_other_family_hits = 0
      validation_heldout_hits = "4 of 60"
      hash1 = "1533acd36572b752f7e3dd1f01ed12ce6cc89491dc8f5a16304e9ce15ebd4ae6"
      hash2 = "78ebd82a7705f72ad48780803cc540ccd240fe04fd2cd4f092445d624e5197df"
      hash3 = "eaad67ae6935cb76b29379c9e17b9d11994b4211dafefb6b55240e908ff4ba8e"
   strings:
      $s1 = "-ExecutionPolicy Bypass -File \"" fullword wide
      $s2 = "SHCore.dll" fullword ascii /* goodware: 4 */
      $s3 = "Transfarencia.exe" fullword ascii
      $s4 = "shutdown.exe /f /s /t 0" fullword wide
      $s5 = "shutdown.exe /f /r /t 0" fullword wide
      $s6 = "\\drivers\\etc\\hosts" fullword wide /* goodware: 1 */
      $s7 = "OfflineKeylogger Not Enabled" fullword wide
      $s8 = "4System.Web.Services.Protocols.SoapHttpClientProtocol" fullword ascii /* goodware: 9 */
      $s9 = "CloseMutex" fullword ascii
      $s10 = "_appMutex" fullword ascii
      $s11 = "ProcessDpi" fullword ascii
      $s12 = "Win32_Processor.deviceid=\"CPU0\"" fullword wide
      $s13 = "shutdown.exe -L" fullword wide
      $s14 = "EXECUTION_STATE" fullword ascii /* goodware: 3 */
      $s15 = "AES_Encryptor" fullword ascii
      $s16 = "userAgents" fullword ascii /* goodware: 4 */
      $s17 = "RunShell" fullword wide /* goodware: 1 */
      $s18 = "GetLastInputTime" fullword ascii /* goodware: 1 */
      $s19 = "GetHashT" fullword ascii
      $s20 = "\\root\\SecurityCenter2" fullword wide /* goodware: 1 */
   condition:
      uint16(0) == 0x5a4d and filesize < 100KB and 8 of ($s*)
}