rule AUTO_asyncrat_b_v1 {
   meta:
      description = "asyncrat: names and string literals shared by the family's .NET builds. Generated by AegisLattice yara-forge and promoted only after 0 hits on 41,717 clean files, 0 hits on other families, and hits on held-out samples it was not built from; monitored in production and retired if precision drops."
      author = "Tao Goldi (AegisLattice yara-forge, generated and validated automatically)"
      reference = "https://taogoldi.github.io/reverse-engineer/"
      license = "MIT"
      family = "asyncrat"
      date = "2026-09-20"
      version = 1
      generator = "yara-forge/dotnet-tokens"
      label_basis = "oracle-labelled samples (decoded config, MOTIF, MCRIT, VirusTotal, abuse.ch)"
      training_samples = 40
      validation_goodware_files = 41717
      validation_goodware_hits = 0
      validation_other_families = 126
      validation_other_family_hits = 0
      validation_heldout_hits = "2 of 60"
      live_precision = "0.94 over 139 matches"
      live_measured = "2026-09-21"
      hash1 = "9b83c0732765e63022102b3e590f0aef07d488a0c967433ef38a8d7648b1fcef"
      hash2 = "4c9d9e12a691c67939525cfbd4bd416ee027602113dd8159e847aaaab9bdd6de"
      hash3 = "93ae860b34d78429fd3f4140cb2ca139bed29fa0f81d99cd35dce8f8024b0f0a"
   strings:
      $t0 = "\\nuR\\noisreVtnerruC\\swodniW\\tfosorciM\\erawtfoS" ascii wide
      $t1 = "1DB2A1F9902B35F8F880EF1692CE9947A193D5A698D8F568BDA721658ED4C58B" ascii wide
      $t2 = "Client.Handle_Packet" ascii wide
      $t3 = "%Certificate%" ascii wide
      $t4 = "%Serversignature%" ascii wide
      $t5 = "/// Client Buffersize" ascii wide
   condition:
      uint16(0) == 0x5a4d and 3 of them
}
