rule AUTO_vidar_a_v2 {
   meta:
      description = "vidar: strings selected by yarGen from the family's samples. Generated by AegisLattice yara-forge and promoted only after 0 hits on 48,864 clean files, 0 hits on other families, and hits on held-out samples it was not built from; monitored in production and retired if precision drops."
      author = "Tao Goldi (AegisLattice yara-forge, generated and validated automatically)"
      reference = "https://taogoldi.github.io/reverse-engineer/"
      license = "MIT"
      family = "vidar"
      date = "2026-09-25"
      version = 2
      generator = "yara-forge/yargen-go"
      label_basis = "oracle-labelled samples (decoded config, MOTIF, MCRIT, VirusTotal, abuse.ch)"
      training_samples = 40
      validation_goodware_files = 48864
      validation_goodware_hits = 0
      validation_other_families = 263
      validation_other_family_hits = 0
      validation_heldout_hits = "3 of 60"
      hash1 = "ec360687d55a94fb637dec26ffcaa58171b1501437db02d0485f86e1812016ae"
      hash2 = "1099c4ef867b15fd5690d44756c55c1e7c3c6f90014e50cdfd12073c022c5745"
      hash3 = "c0b9861aa16d84af9060aa4f09bee129e769978bbe4065c9edfa90be532d2778"
   strings:
      $s1 = "C:\\Users\\Administrator\\Desktop\\UpdateFactory\\compiler\\1.25.0\\go\\src\\runtime\\cgo" fullword ascii
      $s2 = "GODEBUG: value \"permission deniedwrong medium typeno data availableexec format errorLookupAccountSidWDnsRecordListFreeGetCurren" ascii
      $s3 = "Crypt.dll" fullword ascii
      $s4 = "runtime: sp=abi mismatchwrong timerstrace bufferlevel 3 resetsrmount errortimer expiredexchange fullRegEnumKeyExWRegOpenKeyExWCe" fullword ascii
      $s5 = "C:\\Windows\\system32" fullword ascii
      $s6 = "bcryptprimitives.dll not foundpanic called with nil argumentcheckdead: inconsistent countsrunqputslow: queue is not fullruntime:" fullword ascii
      $s7 = "m= sp= sp: lr: fp= gp= mp=) m=boolint8uintchanfuncermsfsrmsse3avx2bmi1bmi2Densepod-1pod-2pod-3ntohsdefersweeptestRtestWexecWhcha" fullword ascii
      $s8 = ".reloc_target" fullword ascii /* goodware: 2 */
      $s9 = " s.sweepgen= allocCount page summaryProcessPrng" fullword ascii /* goodware: 8 */
      $s10 = "runtime: failed to signal runtime initialization complete." fullword ascii /* goodware: 2 */
      $s11 = "internal/sync/mutex.go" fullword ascii /* goodware: 4 */
      $s12 = "C:\\crossdev\\gccmaster\\build-tdm64\\runtime\\mingw-w64-crt" fullword ascii
      $s13 = "main.libintl_dcngettext.func1.2" fullword ascii
      $s14 = "main.libintl_dgettext.func1.1" fullword ascii
      $s15 = "main.libintl_dcgettext.func1.5" fullword ascii
      $s16 = "main.libintl_dngettext" fullword ascii
      $s17 = "main.libintl_dgettext" fullword ascii
      $s18 = "main.libintl_dcgettext.func1.2" fullword ascii
      $s19 = "main.libintl_gettext" fullword ascii
      $s20 = "main.libintl_dcngettext" fullword ascii
   condition:
      uint16(0) == 0x5a4d and filesize < 9000KB and 8 of ($s*)
}