rule AUTO_njrat_a_v1 {
   meta:
      description = "njrat: names and string literals shared by the family's .NET builds. Generated by AegisLattice yara-forge and promoted only after 0 hits on 41,717 clean files, 0 hits on other families, and hits on held-out samples it was not built from; monitored in production and retired if precision drops."
      author = "Tao Goldi (AegisLattice yara-forge, generated and validated automatically)"
      reference = "https://taogoldi.github.io/reverse-engineer/"
      license = "MIT"
      family = "njrat"
      date = "2026-09-20"
      version = 1
      generator = "yara-forge/dotnet-tokens"
      label_basis = "oracle-labelled samples (decoded config, MOTIF, MCRIT, VirusTotal, abuse.ch)"
      training_samples = 40
      validation_goodware_files = 41717
      validation_goodware_hits = 0
      validation_other_families = 126
      validation_other_family_hits = 0
      validation_heldout_hits = "13 of 60"
      live_precision = "1.00 over 1121 matches"
      live_measured = "2026-09-24"
      hash1 = "3709e6f489626cd6300e0a4f3506d12d4aea80973bfa8673608b1fa20d2fd71a"
      hash2 = "cd1ab1369c5b2090a046e27574158e038fabdabc695623b3e85810246990e351"
      hash3 = "6ffd1b8b7c4912b4fb0bdb1437371a1e761854092fb0c3e4934d32e9a30d9f38"
   strings:
      $t0 = "Download ERROR" ascii wide
      $t1 = "Execute ERROR" ascii wide
      $t2 = "Executed As" ascii wide
      $t3 = "Update ERROR" ascii wide
      $t4 = "\" ENABLE" ascii wide fullword
      $t5 = "netsh firewall delete allowedprogram \"" ascii wide
   condition:
      uint16(0) == 0x5a4d and 3 of them
}
