rule AUTO_snakekeylogger_a_v3 {
   meta:
      description = "snakekeylogger: strings selected by yarGen from the family's samples. Generated by AegisLattice yara-forge and promoted only after 0 hits on 48,864 clean files, 0 hits on other families, and hits on held-out samples it was not built from; monitored in production and retired if precision drops."
      author = "Tao Goldi (AegisLattice yara-forge, generated and validated automatically)"
      reference = "https://taogoldi.github.io/reverse-engineer/"
      license = "MIT"
      family = "snakekeylogger"
      date = "2026-09-25"
      version = 3
      generator = "yara-forge/yargen-go"
      label_basis = "oracle-labelled samples (decoded config, MOTIF, MCRIT, VirusTotal, abuse.ch)"
      training_samples = 40
      validation_goodware_files = 48864
      validation_goodware_hits = 0
      validation_other_families = 263
      validation_other_family_hits = 0
      validation_heldout_hits = "4 of 60"
      hash1 = "e8c96e9b3d270abd9522f17ab7d493d91099e9b0d637b792d686b6536a59ec7e"
      hash2 = "39a4cae35b483e70e69f5536dd47d608576c26809d82c75487ddd87525cd20d5"
      hash3 = "3e4e49ab5d8d4fd1373e94cda322de38e65e9e28089191075a9c7e0084d4989e"
   strings:
      $s1 = "Foxmail.exe" fullword wide /* goodware: 2 */
      $s2 = "\\nss3.dll" fullword wide /* goodware: 2 */
      $s3 = "get_encryptedPassword" fullword ascii
      $s4 = "YFGGCVyufgtwfyuTGFWTVFAUYVF.exe" fullword ascii
      $s5 = "\\GhostBrowser\\User Data\\Default\\Login Data" fullword wide
      $s6 = "logins.json" fullword wide /* goodware: 2 */
      $s7 = "\\mozglue.dll" fullword wide
      $s8 = "Software\\Microsoft\\Windows NT\\CurrentVersion\\Windows Messaging Subsystem\\Profiles\\Outlook\\9375CFF0413111d3B88A00104B2A667" wide
      $s9 = "get_logins" fullword ascii
      $s10 = "DownloaderFile" fullword ascii
      $s11 = "\\Comodo\\Dragon\\User Data\\Default\\Login Data" fullword wide
      $s12 = "BCrypt.BCryptDecrypt() (get size) failed with status code: {0}" fullword wide /* goodware: 4 */
      $s13 = "\\SnakeKeylogger\\" fullword wide
      $s14 = "\\SnakeKeylogger" fullword wide
      $s15 = "ProcessKiller" fullword ascii
      $s16 = "SMTP Password" fullword wide
      $s17 = "set_encryptedPassword" fullword ascii
      $s18 = "get_encryptedUsername" fullword ascii
      $s19 = "SnakeKeylogger" fullword wide
      $s20 = "get_timePasswordChanged" fullword ascii
   condition:
      uint16(0) == 0x5a4d and filesize < 700KB and 8 of ($s*)
}