rule AUTO_snakekeylogger_b_v6 {
   meta:
      description = "snakekeylogger: strings selected by yarGen from the family's samples. Generated by AegisLattice yara-forge and promoted only after 0 hits on 48,864 clean files, 0 hits on other families, and hits on held-out samples it was not built from; monitored in production and retired if precision drops."
      author = "Tao Goldi (AegisLattice yara-forge, generated and validated automatically)"
      reference = "https://taogoldi.github.io/reverse-engineer/"
      license = "MIT"
      family = "snakekeylogger"
      date = "2026-10-10"
      version = 6
      generator = "yara-forge/yargen-go"
      label_basis = "oracle-labelled samples (decoded config, MOTIF, MCRIT, VirusTotal, abuse.ch)"
      training_samples = 40
      validation_goodware_files = 48864
      validation_goodware_hits = 0
      validation_other_families = 450
      validation_other_family_hits = 0
      validation_heldout_hits = "2 of 60"
      hash1 = "c0e8dcf4096de51fec0709a1e6778923be7f5320389e38cf6b93965ef4daa904"
      hash2 = "e8c96e9b3d270abd9522f17ab7d493d91099e9b0d637b792d686b6536a59ec7e"
      hash3 = "39a4cae35b483e70e69f5536dd47d608576c26809d82c75487ddd87525cd20d5"
   strings:
      $s1 = "Hello World!" fullword ascii /* goodware: 1 */
      $s2 = " s495,7B" fullword ascii
   condition:
      uint16(0) == 0x5a4d and filesize < 700KB and all of ($s*)
}