rule AUTO_avemariarat_a_v1 {
   meta:
      description = "avemariarat: strings selected by yarGen from the family's samples. Generated by AegisLattice yara-forge and promoted only after 0 hits on 48,864 clean files, 0 hits on other families, and hits on held-out samples it was not built from; monitored in production and retired if precision drops."
      author = "Tao Goldi (AegisLattice yara-forge, generated and validated automatically)"
      reference = "https://taogoldi.github.io/reverse-engineer/"
      license = "MIT"
      family = "avemariarat"
      date = "2026-09-27"
      version = 1
      generator = "yara-forge/yargen-go"
      label_basis = "oracle-labelled samples (decoded config, MOTIF, MCRIT, VirusTotal, abuse.ch)"
      training_samples = 40
      validation_goodware_files = 48864
      validation_goodware_hits = 0
      validation_other_families = 265
      validation_other_family_hits = 0
      validation_heldout_hits = "6 of 60"
      hash1 = "0911748a95f6a362d1ed8d6fcd1a7889167520cdd506522658d84a69c9a088ab"
      hash2 = "69d962a08c69bee560dae12bf7209a36a8a919bef0b65bf8277c823a5c4e1fd8"
      hash3 = "fee959ff12e4ac5df67164ed83565a768d1286263bed759a32dcbe668ef6390f"
   strings:
      $x1 = "cmd.exe /C ping 1.2.3.4 -n 2 -w 1000 > Nul & Del /f /q " fullword ascii
      $x2 = "cmd.exe /c REG ADD \"HKCU\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Windows\" /f /v Load /t REG_SZ /d \"" fullword ascii
      $x3 = "C:\\Users\\Vitali Kremez\\Documents\\MidgetPorn\\workspace\\MsgBox.exe" fullword wide
      $x4 = "c:\\windows\\system32\\user32.dll" fullword ascii
      $x5 = "C:\\Users\\W7H64\\source\\repos\\Ring3 CRAT x64\\Ring3 CRAT x64\\nope.pdb" fullword ascii
      $x6 = "\\\\?\\C:\\Windows \\System32\\WINMM.dll" fullword wide
      $x7 = "\\\\?\\C:\\Windows \\System32\\winmmd.dll" fullword wide
      $x8 = "termsrv.dll" fullword wide /* goodware: 4, reversed encoded */
      $s9 = "\\System32\\cmd.exe" fullword ascii
      $s10 = "ProcessHacker.exe" fullword wide
      $s11 = "msvcp120.dll" fullword wide /* goodware: 6, reversed encoded */
      $s12 = "msvcr120.dll" fullword wide /* goodware: 8, reversed encoded */
      $s13 = "\\\\?\\C:\\Windows \\System32\\winSAT.exe" fullword wide
      $s14 = "@\\cmd.exe" fullword wide
      $s15 = "C:\\Windows \\System32\\winSAT.exe" fullword wide
      $s16 = "mozglue.dll" fullword wide /* goodware: 1 */
      $s17 = "find.exe" fullword ascii /* goodware: 1 */
      $s18 = "vaultcli.dll" fullword ascii /* goodware: 14, reversed encoded */
      $s19 = "softokn3.dll" fullword wide /* goodware: 4 */
      $s20 = "nss3.dll" fullword wide /* goodware: 5 */
   condition:
      uint16(0) == 0x5a4d and filesize < 500KB and 1 of ($x*) and 4 of ($s*)
}