rule AUTO_gcleaner_a_v1 {
   meta:
      description = "gcleaner: strings selected by yarGen from the family's samples. Generated by AegisLattice yara-forge and promoted only after 0 hits on 41,717 clean files, 0 hits on other families, and hits on held-out samples it was not built from; monitored in production and retired if precision drops."
      author = "Tao Goldi (AegisLattice yara-forge, generated and validated automatically)"
      reference = "https://taogoldi.github.io/reverse-engineer/"
      license = "MIT"
      family = "gcleaner"
      date = "2026-09-22"
      version = 1
      generator = "yara-forge/yargen-go"
      label_basis = "oracle-labelled samples (decoded config, MOTIF, MCRIT, VirusTotal, abuse.ch)"
      training_samples = 40
      validation_goodware_files = 41717
      validation_goodware_hits = 0
      validation_other_families = 241
      validation_other_family_hits = 0
      validation_heldout_hits = "11 of 60"
      live_precision = "1.00 over 17 matches"
      live_measured = "2026-09-24"
      hash1 = "93f739b675520ba69cc39e7c066383e53161b7d9d03e7b287ca52ee4c146b3ed"
      hash2 = "f1e81821f74fc598366bdd9142f237404b7dc7b32c794d9a6d76ebc718d7a20b"
      hash3 = "80a741131bec7b3fc74b4cec678fa45e61760914a9e87c4434cb12f8266df426"
   strings:
      $s1 = "Execute not supported: %s1Operation not allowed on a unidirectional dataset" fullword wide
      $s2 = "Unknown erroreInterBase library gds32.dll not found in the path. Please install InterBase to use this functionalityoInterBase In" fullword wide
      $s3 = "Required Param value not set!No Stored Procedure Name assigned<use ExecProc for Procedure; use TQuery for Select procedures" fullword wide
      $s4 = "IB.SQL.MONITOR.Mutex4_1" fullword ascii
      $s5 = "OLE error %.8x.Method '%s' not supported by automation object/Variant does not reference an automation object7Dispatch methods d" fullword wide /* goodware: 1 */
      $s6 = "vcltest3.dll" fullword ascii /* goodware: 11 */
      $s7 = "Hello World!" fullword ascii /* goodware: 1 */
      $s8 = "Thread Error: %s (%d)" fullword wide /* goodware: 2 */
      $s9 = "LoginPrompt" fullword ascii
      $s10 = "TMSDOMProcessingInstruction" fullword ascii
      $s11 = "3Cannot \"open\" a non-select statement. Use ExecQuery" fullword wide
      $s12 = "get_publicId" fullword ascii /* goodware: 3 */
      $s13 = "Temporary file access error" fullword wide
      $s14 = "Field '%s' has no dataset\"Circular datalinks are not allowed/Lookup information for field '%s' is incomplete0Cannot perform thi" wide
      $s15 = "get_systemId" fullword ascii /* goodware: 3 */
      $s16 = "old_dump_id" fullword ascii
      $s17 = "online_dump" fullword ascii
      $s18 = "read_committed" fullword ascii /* goodware: 2 */
      $s19 = ": :$:(:,:0:4:8:<:@:D:H:L:P:T:X:\\:`:d:h:l:p:~:" fullword ascii /* goodware: 2 */
      $s20 = "PasswordChange" fullword ascii /* goodware: 4 */
   condition:
      uint16(0) == 0x5a4d and filesize < 16000KB and 8 of ($s*)
}