rule AUTO_remcos_a_v1 {
   meta:
      description = "remcos: strings selected by yarGen from the family's samples. Generated by AegisLattice yara-forge and promoted only after 0 hits on 41,717 clean files, 0 hits on other families, and hits on held-out samples it was not built from; monitored in production and retired if precision drops."
      author = "Tao Goldi (AegisLattice yara-forge, generated and validated automatically)"
      reference = "https://taogoldi.github.io/reverse-engineer/"
      license = "MIT"
      family = "remcos"
      date = "2026-09-20"
      version = 1
      generator = "yargen-go"
      label_basis = "oracle-labelled samples (decoded config, MOTIF, MCRIT, VirusTotal, abuse.ch)"
      training_samples = 40
      validation_goodware_files = 41717
      validation_goodware_hits = 0
      validation_other_families = 121
      validation_other_family_hits = 0
      validation_heldout_hits = "7 of 60"
      live_precision = "1.00 over 493 matches"
      live_measured = "2026-09-24"
      hash1 = "e7227b215daa43a3c529f9d9631880b8c20b319f049f081fbfac75011c31ed2b"
      hash2 = "e61e14aaba209be7bfed6b4ef08d1de630fd0b2f05c12eeb3f8906946522e7b9"
      hash3 = "43ee2409e135916fab34e910035ff437eb1eaa670000c4f0948ba33f11a7083b"
   strings:
      $x1 = "C:\\Windows\\System32\\cmd.exe" fullword ascii
      $s2 = "[+] before ShellExec" fullword ascii
      $s3 = "[+] ShellExec success" fullword ascii
      $s4 = "/k %windir%\\System32\\reg.exe ADD HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System /v EnableLUA /t REG_DWOR" ascii
      $s5 = "CreateObject(\"WScript.Shell\").Run \"cmd /c \"\"" fullword wide
      $s6 = "[+] ucmCMLuaUtilShellExecMethod" fullword ascii
      $s7 = "PowrProf.dll" fullword ascii /* goodware: 3 */
      $s8 = "\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\" fullword ascii
      $s9 = "[-] CoGetObject FAILURE" fullword ascii
      $s10 = "ielowutil.exe" fullword wide /* goodware: 5 */
      $s11 = "rmclient.exe" fullword wide
      $s12 = "\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Login Data" fullword ascii
      $s13 = "fso.DeleteFile(Wscript.ScriptFullName)" fullword wide
      $s14 = "Keylogger initialization failure: error " fullword ascii
      $s15 = "[+] CoGetObject SUCCESS" fullword ascii
      $s16 = "[+] CoGetObject" fullword ascii
      $s17 = "[Chrome StoredLogins found, cleared!]" fullword ascii
      $s18 = "[Firefox StoredLogins Cleared!]" fullword ascii
      $s19 = "CreateObject(\"Scripting.FileSystemObject\").DeleteFile(Wscript.ScriptFullName)" fullword wide
      $s20 = "Online Keylogger Stopped" fullword ascii
   condition:
      uint16(0) == 0x5a4d and filesize < 2000KB and 1 of ($x*) and 4 of ($s*)
}