rule AUTO_nanocore_a_v1 {
   meta:
      description = "nanocore: names and string literals shared by the family's .NET builds. Generated by AegisLattice yara-forge and promoted only after 0 hits on 41,717 clean files, 0 hits on other families, and hits on held-out samples it was not built from; monitored in production and retired if precision drops."
      author = "Tao Goldi (AegisLattice yara-forge, generated and validated automatically)"
      reference = "https://taogoldi.github.io/reverse-engineer/"
      license = "MIT"
      family = "nanocore"
      date = "2026-09-20"
      version = 1
      generator = "yara-forge/dotnet-tokens"
      label_basis = "oracle-labelled samples (decoded config, MOTIF, MCRIT, VirusTotal, abuse.ch)"
      training_samples = 40
      validation_goodware_files = 41717
      validation_goodware_hits = 0
      validation_other_families = 126
      validation_other_family_hits = 0
      validation_heldout_hits = "8 of 60"
      live_precision = "1.00 over 187 matches"
      live_measured = "2026-09-24"
      hash1 = "a2d004f78528c839119532cff09cf6f777baea9b1680d69eeb82d6a7700690db"
      hash2 = "04c147559ea23daa59503c0b935c8df2728893ea82211813c8428b630fcd3768"
      hash3 = "7cdd2a796b1b8de7131deadb7a9d6b348d321ce6b7af022124b0826166f70c18"
   strings:
      $t0 = "#=q$JqWZLd6UPV3jmsDHksd2EmkHWISQtPlvGx8vZ7hHXE=" ascii wide
      $t1 = "#=q$P4U7B6$qbq6QJ_QX8MfyNoxYRq3foNT$OZzr5yEqDQ=" ascii wide
      $t2 = "#=q$XurN5kwCvUuDGDncP4myluEGVmoB5AfvTb_Ct0PT5c=" ascii wide
      $t3 = "#=q$XxqrIH7dyYqacMzR_CjGA5JAR0vUKiq1f0DFqS1mcI=" ascii wide
      $t4 = "#=q$bBbU_xpGfMMkAvp45SBRg==" ascii wide
      $t5 = "#=q$c3lXLbhl3Qzil6Z9hYEopCTRdsG8WE_1ZuhF2KQELQ=" ascii wide
   condition:
      uint16(0) == 0x5a4d and 3 of them
}
