rule AUTO_a310logger_a_v1 {
   meta:
      description = "a310logger: strings selected by yarGen from the family's samples. Generated by AegisLattice yara-forge and promoted only after 0 hits on 48,864 clean files, 0 hits on other families, and hits on held-out samples it was not built from; monitored in production and retired if precision drops."
      author = "Tao Goldi (AegisLattice yara-forge, generated and validated automatically)"
      reference = "https://taogoldi.github.io/reverse-engineer/"
      license = "MIT"
      family = "a310logger"
      date = "2026-09-27"
      version = 1
      generator = "yara-forge/yargen-go"
      label_basis = "oracle-labelled samples (decoded config, MOTIF, MCRIT, VirusTotal, abuse.ch)"
      training_samples = 40
      validation_goodware_files = 48864
      validation_goodware_hits = 0
      validation_other_families = 265
      validation_other_family_hits = 0
      validation_heldout_hits = "10 of 60"
      hash1 = "8d9f8265ce85222ef929005522d3c45fc185cccd1ffca0b365ef3b2b165d7868"
      hash2 = "e452b95b8707139fccb98f931901ef3a77b8a199e7fa8e421e4e0a66f8cf0cc4"
      hash3 = "f79bbbb5426834f7b541a87414c3f9c319d8e1ea2c8bfcef4ec880a8bbb69332"
   strings:
      $s1 = "Reflect.exe" fullword ascii
      $s2 = "vcltest3.dll" fullword ascii /* goodware: 11 */
      $s3 = "7z7m7h7[7V7I7D77727%7 7" fullword ascii /* reversed encoded */
      $s4 = "2|2d2`2\\2X2T2P2L2H2D2@2<2824202,2(2$2 2" fullword ascii /* reversed encoded */
      $s5 = "1x1p1h1`1X1P1H1" fullword ascii /* reversed encoded */
      $s6 = "1Y1R1(1!1" fullword ascii /* reversed encoded */
      $s7 = "7E7A7=7975717-7)7%7!7" fullword ascii /* reversed encoded */
      $s8 = "        processorArchitecture=\"*\"/>" fullword ascii /* goodware: 1 */
      $s9 = "2|2x2t2p2l2d2D202,2(2$2 2" fullword ascii /* reversed encoded */
      $s10 = "4x4X4D4@4<4844404,4(4$4" fullword ascii /* reversed encoded */
      $s11 = "clWebDarkMagenta" fullword ascii
      $s12 = "10/.-,+*)(" fullword ascii /* reversed encoded */
      $s13 = "5p5X5T5P5L5H5D5@5<58505" fullword ascii /* reversed encoded */
      $s14 = "Invalid ImageList Index)Failed to read ImageList data from stream(Failed to write ImageList data to stream$Error creating window" fullword wide /* goodware: 2 */
      $s15 = "<<< Copyright (c) Delphi TARGA Loader v0.2 by XProger >>>" fullword ascii
      $s16 = "Alt+ Clipboard does not support Icons/Menu '%s' is already being used by another form" fullword wide
      $s17 = "Write$Error creating variant or safe array!'%s' is not a valid integer value" fullword wide
      $s18 = "Stream write error\"Unable to find a Table of Contents" fullword wide
      $s19 = "2$2@2D2L2P2T2X2\\2`2d2h2l2t2" fullword ascii /* hex encoded */
      $s20 = "A class named %s already exists%List does not allow duplicates ($0%x)#A component named %s already exists%String list does not a" fullword wide /* goodware: 2 */
   condition:
      uint16(0) == 0x5a4d and filesize < 5000KB and 8 of ($s*)
}