rule AUTO_a310logger_b_v1 {
   meta:
      description = "a310logger: strings selected by yarGen from the family's samples. Generated by AegisLattice yara-forge and promoted only after 0 hits on 48,864 clean files, 0 hits on other families, and hits on held-out samples it was not built from; monitored in production and retired if precision drops."
      author = "Tao Goldi (AegisLattice yara-forge, generated and validated automatically)"
      reference = "https://taogoldi.github.io/reverse-engineer/"
      license = "MIT"
      family = "a310logger"
      date = "2026-09-27"
      version = 1
      generator = "yara-forge/yargen-go"
      label_basis = "oracle-labelled samples (decoded config, MOTIF, MCRIT, VirusTotal, abuse.ch)"
      training_samples = 40
      validation_goodware_files = 48864
      validation_goodware_hits = 0
      validation_other_families = 265
      validation_other_family_hits = 0
      validation_heldout_hits = "7 of 60"
      hash1 = "8d9f8265ce85222ef929005522d3c45fc185cccd1ffca0b365ef3b2b165d7868"
      hash2 = "e452b95b8707139fccb98f931901ef3a77b8a199e7fa8e421e4e0a66f8cf0cc4"
      hash3 = "f79bbbb5426834f7b541a87414c3f9c319d8e1ea2c8bfcef4ec880a8bbb69332"
   strings:
      $s1 = "vcltest3.dll" fullword ascii /* goodware: 11 */
      $s2 = "1|1t1l1d1\\1T1L1D1<141,1$1" fullword ascii /* reversed encoded */
      $s3 = "2~2v2n2f2^2V2N2F2>262.2&2" fullword ascii /* reversed encoded */
      $s4 = "clWebDarkMagenta" fullword ascii
      $s5 = "4x4n4d4Z4P4F4<424(4" fullword ascii /* reversed encoded */
      $s6 = ";v;q;d;_;R;M;@;;;.;);" fullword ascii /* reversed encoded */
      $s7 = "2|2x2t2p2l2h2d2`2\\2X2T2P2L2H2D2@2<282" fullword ascii /* reversed encoded */
      $s8 = "=s=n=a=\\=O=J===8=+=&=" fullword ascii /* reversed encoded */
      $s9 = "0x0p0h0`0X0P0H0@08000(0 0" fullword ascii /* reversed encoded */
      $s10 = "0|0t0l0d0\\0T0L0D0<040,0$0" fullword ascii /* reversed encoded */
      $s11 = "4~4v4n4f4^4V4N4F4>464.4&4" fullword ascii /* reversed encoded */
      $s12 = "        processorArchitecture=\"*\"/>" fullword ascii /* goodware: 1 */
      $s13 = "3~3v3n3f3^3V3N3F3>363.3&3" fullword ascii /* reversed encoded */
      $s14 = "3v3l3b3X3N3D3:303&3" fullword ascii /* reversed encoded */
      $s15 = "Alt+ Clipboard does not support Icons/Menu '%s' is already being used by another form" fullword wide
      $s16 = "Write$Error creating variant or safe array!'%s' is not a valid integer value" fullword wide
      $s17 = "sKernel32" fullword wide /* goodware: 1 */
      $s18 = "Invalid ImageList Index)Failed to read ImageList data from stream(Failed to write ImageList data to stream$Error creating window" fullword wide /* goodware: 2 */
      $s19 = "OnGetSiteInfoH" fullword ascii /* goodware: 2 */
      $s20 = "A class named %s already exists%List does not allow duplicates ($0%x)#A component named %s already exists%String list does not a" fullword wide /* goodware: 2 */
   condition:
      uint16(0) == 0x5a4d and filesize < 5000KB and 8 of ($s*)
}