rule AUTO_a310logger_c_v1 {
   meta:
      description = "a310logger: strings selected by yarGen from the family's samples. Generated by AegisLattice yara-forge and promoted only after 0 hits on 48,864 clean files, 0 hits on other families, and hits on held-out samples it was not built from; monitored in production and retired if precision drops."
      author = "Tao Goldi (AegisLattice yara-forge, generated and validated automatically)"
      reference = "https://taogoldi.github.io/reverse-engineer/"
      license = "MIT"
      family = "a310logger"
      date = "2026-09-27"
      version = 1
      generator = "yara-forge/yargen-go"
      label_basis = "oracle-labelled samples (decoded config, MOTIF, MCRIT, VirusTotal, abuse.ch)"
      training_samples = 40
      validation_goodware_files = 48864
      validation_goodware_hits = 0
      validation_other_families = 265
      validation_other_family_hits = 0
      validation_heldout_hits = "3 of 60"
      hash1 = "8d9f8265ce85222ef929005522d3c45fc185cccd1ffca0b365ef3b2b165d7868"
      hash2 = "e452b95b8707139fccb98f931901ef3a77b8a199e7fa8e421e4e0a66f8cf0cc4"
      hash3 = "f79bbbb5426834f7b541a87414c3f9c319d8e1ea2c8bfcef4ec880a8bbb69332"
   strings:
      $x1 = "C:\\Users\\Public\\Libraries\\vbsqlite3.dll" fullword ascii
      $x2 = "C:\\\\Users\\Public\\strEncodedData.vbs" fullword wide
      $x3 = "C:\\\\Users\\Public\\strEncodedData.txt" fullword wide
      $x4 = "F*\\AC:\\Users\\Administrator\\AppData\\Roaming\\Microsoft\\Windows\\Templates\\Stub\\Project1.vbp" fullword wide
      $x5 = "C:\\\\Users\\Public\\Edge.txt" fullword wide
      $x6 = "C:\\\\Users\\Public\\Brave.txt" fullword wide
      $x7 = "C:\\\\Users\\Public\\chrome.txt" fullword wide
      $s8 = "C:\\Users\\user\\source\\repos\\ConsoleApplication1\\Release\\ConsoleApplication1.pdb" fullword ascii
      $s9 = "SELECT hostname, encryptedUsername, encryptedPassword  FROM moz_logins" fullword wide
      $s10 = "C:\\Users\\Public\\" fullword ascii
      $s11 = "VBA6.DLL" fullword ascii /* goodware: 1 */
      $s12 = "brave.exe" fullword wide /* goodware: 1 */
      $s13 = "winsqlite3.dll" fullword ascii /* goodware: 12, reversed encoded */
      $s14 = "    Chr(34) & WScript.ScriptFullName & Chr(34) & \" /elevated\", \"\", \"runas\", 1" fullword wide
      $s15 = "Foxmail.exe" fullword wide /* goodware: 2 */
      $s16 = "wscript.exe" fullword wide /* goodware: 22, reversed encoded */
      $s17 = "VBSQLite3.dll" fullword ascii
      $s18 = "    CreateObject(\"Shell.Application\").ShellExecute \"wscript.exe\", _" fullword wide
      $s19 = "flight.exe" fullword wide
      $s20 = "AvastBrowser.exe" fullword wide
   condition:
      uint16(0) == 0x5a4d and filesize < 2000KB and 1 of ($x*) and 4 of ($s*)
}