rule AUTO_darkcloud_a_v1 {
   meta:
      description = "darkcloud: strings selected by yarGen from the family's samples. Generated by AegisLattice yara-forge and promoted only after 0 hits on 48,864 clean files, 0 hits on other families, and hits on held-out samples it was not built from; monitored in production and retired if precision drops."
      author = "Tao Goldi (AegisLattice yara-forge, generated and validated automatically)"
      reference = "https://taogoldi.github.io/reverse-engineer/"
      license = "MIT"
      family = "darkcloud"
      date = "2026-09-26"
      version = 1
      generator = "yara-forge/yargen-go"
      label_basis = "oracle-labelled samples (decoded config, MOTIF, MCRIT, VirusTotal, abuse.ch)"
      training_samples = 40
      validation_goodware_files = 48864
      validation_goodware_hits = 0
      validation_other_families = 263
      validation_other_family_hits = 0
      validation_heldout_hits = "42 of 60"
      hash1 = "9e4efb8300d61fa29a18a9169965c531fc547234d3ced0532aa341f899801621"
      hash2 = "91ce11dba631a9613d7c96409db89bf0cc358eff124632ad56f25fd6b372b070"
      hash3 = "9eb48972a13c1c27cfd7f23e517321655648e5796bd26850d255d4a12b91fff9"
   strings:
      $x1 = "C:\\Users\\Public\\Libraries\\vbsqlite3.dll" fullword ascii
      $s2 = "\\winsqlite3.dll" fullword wide
      $s3 = "SysWOW64\\winsqlite3.dll" fullword wide
      $s4 = "HKEY_LOCAL_MACHINE\\SOFTWARE\\Classes\\Foxmail.url.mailto\\Shell\\open\\command\\" fullword wide
      $s5 = "SELECT origin_url, username_value, password_value, length(password_value)  FROM logins" fullword wide
      $s6 = "SELECT origin_url, username_value, password_value  FROM logins" fullword wide
      $s7 = "\\User Data\\Default\\Login Data" fullword wide
      $s8 = "sqlite_exec" fullword ascii /* goodware: 1 */
   condition:
      (uint16(0) == 0x5a4d and filesize < 2000KB and 1 of ($x*) and all of ($s*))
      or (all of them)
}