rule AUTO_smokeloader_a_v2 {
   meta:
      description = "smokeloader: strings selected by yarGen from the family's samples. Generated by AegisLattice yara-forge and promoted only after 0 hits on 41,717 clean files, 0 hits on other families, and hits on held-out samples it was not built from; monitored in production and retired if precision drops."
      author = "Tao Goldi (AegisLattice yara-forge, generated and validated automatically)"
      reference = "https://taogoldi.github.io/reverse-engineer/"
      license = "MIT"
      family = "smokeloader"
      date = "2026-09-22"
      version = 2
      generator = "yara-forge/yargen-go"
      label_basis = "oracle-labelled samples (decoded config, MOTIF, MCRIT, VirusTotal, abuse.ch)"
      training_samples = 40
      validation_goodware_files = 41717
      validation_goodware_hits = 0
      validation_other_families = 241
      validation_other_family_hits = 0
      validation_heldout_hits = "4 of 60"
      hash1 = "215e8de734ec872836c1b451178b7f54e4f3c366bd5b48e9e9cea3a9d1b9c16a"
      hash2 = "bc10bd71d75d2364e4768251e59a5e2e1fc0077e264f1aa3c7d41892143c2ad2"
      hash3 = "778664b87ac10a5e543c2cda87aab48917a21162109131360845b9c10e2f826b"
   strings:
      $s1 = "GODEBUG: value \"permission deniedwrong medium typeno data availableexec format errorLookupAccountSidWDnsRecordListFreeGetCurren" ascii
      $s2 = "7zS.sfx.exe" fullword wide
      $s3 = "bcryptprimitives.dll not foundpanic called with nil argumentcheckdead: inconsistent countsrunqputslow: queue is not fullruntime:" fullword ascii
      $s4 = "C:\\Windows\\system32" fullword ascii
      $s5 = "m= sp= sp: lr: fp= gp= mp=) m=boolint8uintchanfunckind on ermsfsrmsse3avx2bmi1bmi2venuspowerorbitntohsdefersweeptestRtestWexecWh" fullword ascii
      $s6 = " s.sweepgen= allocCount page summaryProcessPrng" fullword ascii /* goodware: 8 */
      $s7 = "internal/sync/mutex.go" fullword ascii /* goodware: 4 */
      $s8 = "ReaderAt" fullword ascii /* goodware: 1 */
      $s9 = "runtime.SetFinalizer: second argument is gcSweep being done but phase is not GCoffobjects added out of order or overlappingmheap" fullword ascii
      $s10 = "unlock: lock countprogToPointerMask: overflowfailed to set sweep barrierwork.nwait was > work.nproc not in stack roots range [al" fullword ascii
      $s11 = "mheap.freeSpanLocked - invalid free of user arena chunkcasfrom_Gscanstatus:top gp->status is not in scan state is currently not " fullword ascii /* goodware: 1 */
      $s12 = "runtime.computeMaxProcsLock" fullword ascii /* goodware: 7 */
      $s13 = "runtime.finexecuted" fullword ascii /* goodware: 7 */
      $s14 = "main.Commodity.func1.21" fullword ascii
      $s15 = "main.Commodity.func1.17" fullword ascii
      $s16 = "main.Commodity.func4.23" fullword ascii
      $s17 = "main.Comfortable.func1" fullword ascii
      $s18 = "main.Comfortable.func1.12" fullword ascii
      $s19 = "main.Comfortable.func1.Comfortable.func1.12.15" fullword ascii
      $s20 = "main.Comfortable.func1.Comfortable.func1.12.16" fullword ascii
   condition:
      uint16(0) == 0x5a4d and filesize < 26000KB and 8 of ($s*)
}